name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  static-checks:
    name: "Static checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Scony/godot-gdscript-toolkit@master

      - name: Check linting
        run: gdlint src/addons/worldeditor/classes

      - name: Check formatting
        run: gdformat --check src/addons/worldeditor/classes
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MikeSchulze/gdUnit4-action@v1.0.5
        with:
          godot-version: '4.2.1'
          godot-net: 'true'
          project_dir: 'src'
          paths: 'res://addons/worldedit/tests'
          
