name: Static checks

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  static-checks:
    name: "Static checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Scony/godot-gdscript-toolkit@master

      - name: Check linting
        run: gdlint src/addons/worldeditor/classes

      - name: Check formatting
        run: gdformat --check src/addons/worldeditor/classes
